add_newline = true

[character]
success_symbol = "ğŸºğŸº"
error_symbol = "ğŸ‘»ğŸ‘»ğŸ‘»"

[memory_usage]
disabled = false 
threshold = -1
#symbol = ""
style = "green"
format = "via $symbol[${ram}( | ${swap})]($style) "

[docker_context]
disabled = true

[aws]
disabled = true
#format = "on [$symbol$profile]($style) "
symbol = "ğŸ…° "

[battery]
disabled = false
full_symbol = "ğŸ”‹ "
charging_symbol = "âš¡ï¸ "
discharging_symbol = "ğŸ’€ "

